apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebappdeploy
spec:
  replicas: 4
  strategy:
    type: Recreate
  selector:
    matchLabels:
     app: javawebapp
  template:
    metadata:
      name: javawebapppod
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javawebappcontainer
        image: agunuworld/java-web-app:22
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: javawebapppodsvc
spec:
  type: LoadBalancer
  selector:
    app: javawebapp
  ports:
  - port: 80
    targetPort: 8080

